version: 2
jobs:
  deploy:
    docker:
      - image: circleci/node:9.11.2
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run:
          name: install packages
          command: npm install
      - run:
          name: Build production code
          command: npm run build
      - run:
          name: Directory update
          command: ssh -o "StrictHostKeyChecking no" -p 5522 deploy@193.40.102.19 'cd /var/www/sarv-edit-dev/script && . directory_update.sh'
      - run:
          name: Copy built files to production server
          command: scp -P 5522 -r dist/* deploy@193.40.102.19:/var/www/sarv-edit-dev
      - save_cache:
          paths:
            - node_modules
            - package.json
          key: v1-dependencies-{{ checksum "package.json" }}

workflows:
  version: 2
  -deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: master
