version: 2
jobs:
  build-test-deploy:
    docker:
      - image: circleci/node:9.11.2
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2.0-dependencies-{{ checksum "package.json" }}
            - v2.0-dependencies-
      - run:
          name: install packages
          command: npm install
      - run:
          name: unit test application
          command: npm run test:unit
      - run:
          name: Build production code
          command: npm run build
      - run:
          name: Directory update
          command: ${DIRECTORY_UPDATE}
      - run:
          name: Copy built files to development
          command: ${COPY_FILES_DEV_1}
      - save_cache:
          paths:
            - node_modules
            - package.json
          key: v2.0-dependencies-{{ checksum "package.json" }}


workflows:
  version: 2
  sarv-edit:
    jobs:
      - build-test-deploy:
          filters:
            branches:
              only: master
