version: 2
jobs:
  deploy:
    docker:
      - image: circleci/node:9.11.2
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run:
          name: install packages
          command: npm install
      - add_ssh_keys:
          - fingerprints:
              - "da:37:31:66:0f:b9:99:16:61:2a:af:0b:ec:e2:95:d5"
      - run:
          name: run deploy script
          command: ./deploy.sh
      - save_cache:
          paths:
            - node_modules
            - package.json
          key: v1-dependencies-{{ checksum "package.json" }}

workflows:
  version: 2
  -deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: master
