version: 2
jobs:
  install_and_cache:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2.4-dependencies-{{ checksum "package.json" }}
            - v2.4-dependencies-
      - run:
          name: Install packages
          command: npm install
      - save_cache:
          paths:
            - node_modules
            - package.json
          key: v2.4-dependencies-{{ checksum "package.json" }}

#  unit_test:
#    docker:
#      - image: circleci/node:latest
#    steps:
#      - checkout
#      - restore_cache:
#          keys:
#            - v2.3-dependencies-{{ checksum "package.json" }}
#            - v2.3-dependencies-
#      - run:
#          name: Unit test application
#          command: npm run test:unit

  build_and_deploy:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2.4-dependencies-{{ checksum "package.json" }}
            - v2.4-dependencies-
      - run:
          name: Build production code
          command: npm run build
      - run:
          name: Directory update
          command: ssh -o "StrictHostKeyChecking no" -p ${PORT} ${USER}@${ADDRESS_1} 'cd /var/www/sarv-edit-dev/script && . directory_update.sh'
      - run:
          name: Copy built files to development
          command: scp -P ${PORT} -r dist/* ${USER}@${ADDRESS_1}:/var/www/sarv-edit-dev

workflows:
  version: 2
  sarv-edit:
    jobs:
      - install_and_cache
#      - unit_test:
#          requires:
#            - install_and_cache
      - build_and_deploy:
          requires:
#            - unit_test
            - install_and_cache
          filters:
            branches:
              only: master
