version: 2
jobs:
  install_and_cache:
    docker:
      - image: circleci/node:9.11.2
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2.1-dependencies-{{ checksum "package.json" }}
            - v2.1-dependencies-
      - run:
          name: install packages
          command: npm install
      - save_cache:
          paths:
            - node_modules
            - package.json
          key: v2.1-dependencies-{{ checksum "package.json" }}

  unit_test:
    docker:
      - image: circleci/node:9.11.2
      steps:
        - checkout
        - restore_cache:
            keys:
              - v2.1-dependencies-{{ checksum "package.json" }}
              - v2.1-dependencies-
        - run:
            name: unit test application
            command: npm run test:unit

  build_and_deploy:
    docker:
      - image: circleci/node:9.11.2
      steps:
        - checkout
        - restore_cache:
            keys:
              - v2.1-dependencies-{{ checksum "package.json" }}
              - v2.1-dependencies-
        - run:
            name: build production code
            command: npm run build
        - run:
            name: Directory update
            command: ${DIRECTORY_UPDATE}
        - run:
            name: Copy built files to development
            command: ${COPY_FILES_DEV_1}

workflows:
  version: 2
  sarv-edit:
    jobs:
      - install_and_cache:
      - unit_test:
          requires:
            - install_and_cache
      - build_and_deploy:
          requires:
            - unit_test
          filters:
            branches:
              only: master
