version: 2
jobs:
  install_build_deploy:
    docker:
      - image: circleci/node:current
    steps:
      - checkout
      - restore_cache:
          keys:
            - v3.0-dependencies-{{ checksum "package.json" }}
            - v3.0-dependencies-
      - run:
          name: Install packages
          command: npm install
      - run:
          name: Build production code
          command: npm run build
      - run:
          name: Directory update
          command: ssh -o "StrictHostKeyChecking no" -p ${PORT} ${USER}@${ADDRESS_1} 'cd /var/www/sarv-edit-dev/script && . directory_update.sh'
      - run:
          name: Copy built files to development
          command: scp -P ${PORT} -r dist/* ${USER}@${ADDRESS_1}:/var/www/sarv-edit-dev
      - save_cache:
          paths:
            - node_modules
            - package.json
          key: v3.0-dependencies-{{ checksum "package.json" }}

workflows:
  version: 2
  sarv-edit:
    jobs:
      - install_build_deploy
