version: 2
jobs:
  build:
    docker:
      - image: circleci/node:current
    parallelism: 2
    working_directory: ~/geocollections/sarv-edit
    steps:
      - checkout
      - attach_workspace:
          at: ~/geocollections/sarv-edit
      - restore_cache:
          key: v1-dependencies-{{ checksum "package-lock.json" }}
      - run:
          name: Install packages
          command: npm install
      - save_cache:
          key: v1-dependencies-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: Build production code
          command: npm run build
      - persist_to_workspace:
          root: .
          paths: dist
  depoloy:
    docker:
      - image: circleci/node:current
    parallelism: 2
    working_directory: ~/geocollections/sarv-edit
    steps:
      - checkout
      - attach_workspace:
          at: ~/geocollections/sarv-edit
      - run:
          name: Directory update
          command: ssh -o "StrictHostKeyChecking no" -p ${PORT} ${USER}@${ADDRESS_1} 'cd /var/www/sarv-edit-dev/script && . directory_update.sh'
      - run:
          name: Copy built files to development
          command: scp -P ${PORT} -r dist/* ${USER}@${ADDRESS_1}:/var/www/sarv-edit-dev


workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
